### ISSUE TITLE
Last unit does not have enough valid bits 错误

### ISSUE THREAD

**Issue by baisheng** [chinayin/WeworkChatSDK#4]
c.c.w.c.service.impl.EncryptServiceImpl  : decodeEncryptRandomKey failed, Last unit does not have enough valid bits

您好，出现这个错误，是配置问题还是 Base64解码出现的问题？

**Comment by baisheng** [comment]
由于配置 privatekey 时，把 “-----BEGIN PRIVATE KEY-----” 头尾标识加入后报的错误。

**Comment by chinayin** [comment]
是的  我配置key的时候没有加 --- 那段   我看下处理
